##need two db

version: '3.8'
services:
  source_postgres:
    image: postgres:17 ##HAD TO DOWNGRADE DUE TO ERROR THAT POSTGRES 18 DID NOT MATCH WITH PG_DUMP 17.7. COULDNT FIND A WAY TO FORCE PG_DUMP VERSION
    ports:
      - "5433:5432"
    networks:
      - elt_network
    environment:
      - POSTGRES_DB=source_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql




  destination_postgres:
    image: postgres:17
    ports:
      - "5434:5432"
    networks:
      - elt_network
    environment:
      - POSTGRES_DB=destination_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  elt_script: 
    build:
      context: ./elt_script
      dockerfile: Dockerfile
    command: ["python", "elt_script.py"]
    networks:
      - elt_network
    depends_on:
      source_postgres:
        condition: service_healthy
      destination_postgres:
        condition: service_healthy

   
networks:
  elt_network:
   driver: bridge